name = "familyhub-pages"
compatibility_date = "2024-10-01"
pages_build_output_dir = "./public"

kv_namespaces = [
  { binding = "HUB_DATA", id = "HUB_DATA_PROD", preview_id = "HUB_DATA_DEV" }
]

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "FamilyRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["FamilyRoom"]
